### ISSUE TITLE
Unicode for the QRL 

### ISSUE THREAD

**Issue by ksangsu95** [theQRL/docs.theqrl.org#27]
In order for QRL to reach the legitimate state of cryptocurrency, I thought that we needed a symbol for QRL unicode. In my opinion, the symbol can be shaped by combining binary numbers 0 and 1. The logo symbolizes quantum superposition state which simultaneously works as both 0 and 1. 

Here's the sample for QRL unicode symbol ('shor' unit) that I've designed:

![untitled diagram 4](https://user-images.githubusercontent.com/36453059/38461936-62e6ce0e-3add-11e8-810a-1ae2b97a54aa.png)

e.g. https://en.bitcoin.it/wiki/Bitcoin_symbol

**Comment by jplomas** [comment]
This should be reworked as a QIP
