### ISSUE TITLE
 OTS document formatting typo

### ISSUE THREAD

**Issue by fr1t2** [theQRL/docs.theqrl.org#82]
Document states (n = 2h)  which obviously should be n=2^h.
 
Thanks discord user @Breus#1005 for pointing this out!

**Comment by jackalyst** [comment]
Looks like this was resolved.
![Screenshot from 2021-08-03 10-57-50](https://user-images.githubusercontent.com/232510/128055888-5e0a3efb-3b6a-4887-b6c1-ad7cc26e71f6.png)
